management:
  context-path: /sysinfo
spring:
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
        hbm2ddl:
          import_files: import_data.sql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sklepy_e_strix_com?useUnicode=yes&characterEncoding=UTF-8
    username: sklepy
    password: 1QAZse4rfv123)
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    testOnBorrow: true
    validationQuery: SELECT 1
hibernate:
  archive:
    autodetection: class
logging:
  level:
    ROOT: ERROR
    org:
      springframework:
        data: ERROR
      hibernate:
        type: ERROR
    pl:
      estrix: trace
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /root/srv/store-sync2/logs/application.log
server:
  port : 8090
  session-timeout : 1800