management:
  context-path: /sysinfo
spring:
    main:
        banner-mode: off
    output:
        ansi:
            enabled: ALWAYS
    jpa:
        database: MYSQL
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                hbm2ddl:
                  import_files: import_data.sql
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/store_sync2?useUnicode=yes&characterEncoding=UTF-8
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver
        testWhileIdle: true
        testOnBorrow: true
        validationQuery: SELECT 1
hibernate:
    archive:
        autodetection: class
logging:
    level:
        ROOT: ERROR
        org:
            springframework:
                data: ERROR
            hibernate:
                type: ERROR
        pl:
            estrix: trace
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: ./application.log
server:
    port : 8090
    session-timeout : 1800