management:
  context-path: /sysinfo
spring:
    main:
        banner-mode: off
    output:
        ansi:
            enabled: ALWAYS
    jpa:
#        database: FIREBIRD
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.FirebirdDialect
                hbm2ddl:
                  import_files: import_data.sql
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:firebirdsql://localhost:3050/C:\\firebird\\storesync2.GDB?charSet=UTF-8
        username: SYSDBA
        password: masterkey
        driver-class-name: org.firebirdsql.jdbc.FBDriver
        testWhileIdle: true
        testOnBorrow: true
        validationQuery: SELECT 1
hibernate:
    archive:
        autodetection: class
logging:
    level:
        ROOT: ERROR
        org:
            springframework:
                data: ERROR
            hibernate:
                type: ERROR
        pl:
            estrix: trace
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: ./application.log
server:
    port : 8090
    session-timeout : 1800